x-base_jupyter: &base_jupyter
  build:
    context: .
  ports:
    - "${PORT:-8888}:8888"
  command: >
    jupyter lab --ip=${JUPYTER_IP:-0.0.0.0} --no-browser --allow-root 
    --NotebookApp.token='${JUPYTER_TOKEN:-}' --NotebookApp.password='${JUPYTER_PASSWORD:-}' 
    --ServerApp.disable_check_xsrf=True
  volumes:
    - ./work:/home/jovyan/work

services:
  cuda:
    <<: *base_jupyter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - cuda

  cpu:
    <<: *base_jupyter
    profiles:
      - cpu
